[window]
width = 800
height = 600

[maze]
rows = 11 # must be an odd number
cols = 11 # must be an odd number
type = 0  # generation algorithm: 0=dfs, 1=prim

[genetic]
population_size = 500
genome_size = 20
crossover_rate = 0.7
mutation_rate = 0.1
